### ISSUE TITLE
Easy Desktop Notifications with BurntToast

### ISSUE THREAD

**Issue by Windos** [PSPowerHour/PSPowerHour#11]
## Easy Desktop Notifications with BurntToast

* **Name**: Josh King
* **Your Timezone**: UTC+12 / UTC+13 _(Able & happy to participate during local business hours)_
* **Abstract**: Want to easily show notifications on your Windows 10 desktop? It's as easy as "cooking bread" with the [BurntToast](https://powershellgallery.com/packages/BurntToast) PowerShell module!
* **Links**:
  * **BurntToast (Repo)**: https://github.com/Windos/BurntToast
  * **BurntToast (Gallery)**: https://powershellgallery.com/packages/BurntToast
  * **Twitter**: [WindosNZ](https://twitter.com/WindosNZ)
  * **Slack ID**: windosnz
  * **Blog URL**: https://king.geek.nz

**Comment by michaeltlombardi** [comment]
Thank you so much for presenting today!
