### ISSUE TITLE
Raspberry Pi with powershell and IoT module 

### ISSUE THREAD

**Issue by DanielSSilva** [PSPowerHour/PSPowerHour#12]
## PowerShell Core and IoT on Raspberry Pi

* **Name**: Daniel Silva 
* **Abstract**: PowerShell on Raspberry opens a whole new world full of challenges. Check how you can interact with hardware using powershell and some examples of what you can achieve. 
* 
  * **Twitter**: [@DanielSilv9](https://twitter.com/danielSilv9)
  * **Slack ID**: Danielsilva on [powershell.slack.com](bit.ly/psslack)
  * **Blog URL**: [danielsknowledgebase.wordpress.com](danielsknowledgebase.wordpress.com)

**Comment by michaeltlombardi** [comment]
Thank you so much for presenting today!
