### ISSUE TITLE
2018-12-18 1800 UTC Lineup planning

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PSPowerHour/PSPowerHour#123]
Hiyo!

EDIT: Schedule:

Title                                              | IssueNumber | Order | By
-------------------------------------------------- | ----------- | ----- | ---------------
Assert: Write less Pester tests to cover more code | #118        | 01    | @nohwnd
Git Rebase: Don't fear the Rebase-r                | #82         | 02    | @ChrisLGardner
Using PowerShell to extend the GUI                 | #121        | 03    | @Schlauge
7 Reasons To Build a Workplace Module              | #58         | 04    | @potatoqualitee

I've been decompressing before the holidays and completely forgot to post this!

We're looking for 6-8 folks for 1800 UTC on December 18 - let us know here if you're up for this, and which topic you'd like if you have more than one proposed!

cc @ChrisLGardner, @nohwnd, @steviecoaster, @vexx32, @Schlauge, @tomlarse, @potatoqualitee, @MSAdministrator, @mattcushing 

Status:

* Slots available: 7 of 8
* Speakers: @nohwnd

**Comment by nohwnd** [comment]
I’d like to do #118 and if you have empty slots I could also do #114

**Comment by RamblingCookieMonster** [comment]
Yay!  We try to keep it so that we only have one-talk-per-speaker-per-pspowerhour, so we'll aim for #118 - thanks @nohwnd  : D

**Comment by ChrisLGardner** [comment]
I'll do #82 but might be best if I'm on towards the end as I'm going to be in a hotel that day and want to be sure I'm actually somewhere I can present from.

**Comment by mattcushing** [comment]
I want to, but I'm going down to pick up my daughter from college.  Do we
have any planned a few weeks out that I can commit to my calendar?

**Comment by Schlauge** [comment]
I’ll do #121

**Comment by steviecoaster** [comment]
Gonna have to pass on this go 'round, unfortunately.

**Comment by vexx32** [comment]
I need a bit more time to prepare something for the proposals I have, I think, so I'll have to pass this turn around as well. 😄

**Comment by tomlarse** [comment]
This one got a bit too close to christmas for me unfortunately. Too much end of season stuff with the kids' activities. :)

**Comment by potatoqualitee** [comment]
I can do #58
