### ISSUE TITLE
Add a podcast/interview segment at the end of PSPowerHour

### ISSUE THREAD

**Issue by thomasrayner** [PSPowerHour/PSPowerHour#124]
At the end of a PSPowerHour session, especially one where there's only 3-5 presenters, it would be cool to have a chatting segment like the one at the end of the Dec 18, 2018 stream. That way you could feel good about running a session that might have fewer presenters, but still give viewers an hour (or something) of content.

My recommendation would be just to chat with the presenters about the things they presented. If there's nothing else to say, then there's probably some current tech news. Wouldn't have to be long. 10-20 min?

cc @vexx32 @michaeltlombardi

**Comment by potatoqualitee** [comment]
agreed, that was enjoyable

**Comment by vexx32** [comment]
I would even consider perhaps dropping the "standard" down to 6 presenters and just more or less always planning in the 10-20mins of chit chat and Q&A time?

**Comment by devblackops** [comment]
"PSPowerHour B-Sides"

I think it's a good idea. Also gives you a chance for any follow up Q/A or to mention something you may have forgotten during the main presentation.

**Comment by thomasrayner** [comment]
@devblackops totally. A 10 min window doesn't leave much time for Q & A either. Plus it'll take a bit of pressure off of the organizers to find so many presenters.

**Comment by RamblingCookieMonster** [comment]
I like the idea!  As long as @michaeltlombardi is up for it I'm in.  Particularly if we move to some cadence that leaves us with fewer speakers more often than not.  I'll help out more than last time (i.e. not sitting silently) if we do : P

**Comment by michaeltlombardi** [comment]
I'm happy with the move to ~6 presenters and 15m post-chat!

**Comment by RamblingCookieMonster** [comment]
Closing this out - is now pretty much standard, awesome idea!

**Comment by potatoqualitee** [comment]
🎉
