### ISSUE TITLE
2019-02-18 1800 UTC Lineup planning

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PSPowerHour/PSPowerHour#128]
Hi all!

edit: Schedule so far:

Title                                                      | IssueNumber | Order | By                
---------------------------------------------------------- | ----------- | ----- | ------------------
When Runspaces need to have a serious discussion           | #130        | 01    | @FriedrichWeinmann
Do The -Split!                                             | #127        | 02    | @IISResetMe       
Host mkdocs in an Azure Storage Blob                       | #122        | 03    | @tomlarse         
One approach to testing self-contained scripts with Pester | #114        | 04    | @nohwnd           
What's New in the World of Toast?                          | #113        | 05    | @Windos 

We're looking for up to 8 folks for a February 18 @ 1800 UTC PSPowerHour.  We'll be trying a mini podcast / discussion after the demos, for anyone interested in sticking around after their demos (per #124).

ccing folks with open issues:  @mattcushing, @devblackops, @MSAdministrator, @steviecoaster, @vexx32, @nohwnd, @tomlarse, @iisresetme

FYI, we'll also be doing a [2019-02-25 session the next Monday, @ 1800 PST](https://github.com/PSPowerHour/PSPowerHour/issues/129)

**Comment by vexx32** [comment]
I won't be able to do this one, but I'm definitely up for doing the following one at 1800 PST. Think I'd love to do #120 at that point. 😄 

I should be up for hanging out watching this one, though 👉 👉

**Comment by nohwnd** [comment]
I am in with #114

**Comment by FriedrichWeinmann** [comment]
I'd be happy to do #130

**Comment by IISResetMe** [comment]
18:00 UTC sounds excellent, can do #127!

**Comment by Windos** [comment]
@RamblingCookieMonster, I can make either date work and can do #113 

Feel free to use me to fill numbers if needed.

**Comment by IISResetMe** [comment]
@RamblingCookieMonster I'm afraid I won't be able to present tonight, as I've contracted a cold 🤧

**Comment by nohwnd** [comment]
@IISResetMe that sucks, I was looking forward to your presentation. Get well soon!

**Comment by FriedrichWeinmann** [comment]
Damn @IISResetMe , can only agree with @nohwnd on the sentiment.
Get well and remember to file a bug report - you getting a cold just in time for this definitely is one (in more than one sense ;) )
