### ISSUE TITLE
Cancelled: 2019-02-25 1800 PST

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PSPowerHour/PSPowerHour#129]
Hi all!

EDIT: Cancelling.  Looks like two sessions per month will be tough to fill!

We're looking for up to 8 folks for a February 25 @ 1800 PST PSPowerHour.  We'll be trying a mini podcast / discussion after the demos, for anyone interested in sticking around after their demos (per #124).

ccing folks with open issues:  @mattcushing, @devblackops, @MSAdministrator, @steviecoaster, @vexx32, @kjacobsen

FYI, we'll also be doing a [2019-02-18 session the previous Monday, @ 1800 UTC](https://github.com/PSPowerHour/PSPowerHour/issues/128)

**Comment by vexx32** [comment]
I didn't see this link 👀 

But yeah, I'm up for #120 for this one!! 😄

**Comment by devblackops** [comment]
1800 Pacific works for me! I'm down for doing #33.

**Comment by steviecoaster** [comment]
I'll do #119 this go 'round.

**Comment by vexx32** [comment]
@RamblingCookieMonster I've just reviewed my calendar for the week, and unfortunately I have a scheduling conflict for this one, so I'll have to pull out of this one, sorry! :(
