### ISSUE TITLE
2019-06-13 1800 PST Lineup planning

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PSPowerHour/PSPowerHour#139]
Hi all!

We're looking for up to 8 folks for a June 13 @ 1800 PST PSPowerHour.  We'll be trying a mini podcast / discussion after the demos, for anyone interested in sticking around after their demos (per #124).

edit: 3 spots left.  Schedule so far:

Title | IssueNumber | Order | By                
--- | ---  | --- | ---
PowerShell Magic: Argument Transformations | #120 | 1 | @vexx32
Azure Pipelines Speedrun | #135 | 2 | @Windos
Deploy websites and bind vanity certificates in IIS with PowerShell | #137 | 3 | @torque999
Fun with Fonts: Displaying file and folder icons in your terminal | #138 | 4| @devblackops
"Missing" functionality in PowerShell | #140 | 5 | @KirkMunro

ccing folks with open issues:  @mattcushing, @kjacobsen, @devblackops, @MSAdministrator, @steviecoaster, @glennsarti, @vexx32, @nohwnd, @thomasrayner, @iisresetme, @Gaspack, @windos, @torque999

Give us a ping in here if you're up for it!

**Comment by vexx32** [comment]
I'll do #120 for sure!

**Comment by mattcushing** [comment]
Having surgery on the 11th on my hand so controlling a mouse might be
difficult :)  I'm up for the next one tho!

**Comment by Windos** [comment]
I'll do #135! ... going to have to refresh myself on that whole thing lol.

**Comment by torque999** [comment]
I'm still good for #137.  I made sure it works in IIS 8 and 10.  ;-)

**Comment by devblackops** [comment]
I'm down for doing either #138 or #33

**Comment by RamblingCookieMonster** [comment]
Any preference @devblackops?  Either works!

**Comment by steviecoaster** [comment]
I'll be in Disney World chastising a mouse. I'll be down for the next round
😊

**Comment by devblackops** [comment]
@RamblingCookieMonster I'll do #138

**Comment by KirkMunro** [comment]
I'm up for doing #140 if you want it.

**Comment by felixfbecker** [comment]
Does it have to be 18:00 PST? That is 3 AM in CEST (Europe)...
Given that PST is one of the most-west timezones, it would make more sense to me to do it _in the morning_ PST

**Comment by RamblingCookieMonster** [comment]
@KirkMunro adding you now, thanks : D

@felixfbecker - for this session, yes - but we'll schedule one for 1800 UTC for our next hour - if you submit a proposal we'll ping you for that one - cheers!

**Comment by vexx32** [comment]
@RamblingCookieMonster unfortunately I'm not going to be ready for this round. I've not been able to set aside enough time to prepare what I've got the way I want to for the time being. 🙁 

I'll make sure I have stuff prepared for next round, or maybe after depending on how my schedule lines up with whatever time zone we do the next one in. 💖

**Comment by torque999** [comment]
So, this is my first rodeo.  How are we going to do the presentations tonight?

**Comment by vexx32** [comment]
@RamblingCookieMonster will send out both a Youtube link for the viewers and to each of us a private meeting link. I believe we're still using Google Hangouts, it works pretty well directly in the browser.

We'll usually get the meeting link about 30mins or so before start time, and we'll generally want everyone presenting to be there not too long after that if possible, just so we can pre-check everyone's setup, make sure any code they're showing is readable, we can hear you properly, etc. 🙂

**Comment by RamblingCookieMonster** [comment]
@torque999 - can you shoot me you're e-mail?  in PowerShell slack (@ pscookiemonster) or just to warren.frame at gmail - I'll send the stuff @vexx32  mentioned there!
