### ISSUE TITLE
Deploying SQL code using Powershell

### ISSUE THREAD

**Issue by nvarscar** [PSPowerHour/PSPowerHour#18]
## Deploying SQL code using Powershell

* **Name**: Kirill Kravtsov
* **Abstract**: Discover a way of deploying your SQL code in a reliable and repeatable manner by using Powershell deployment module [DBOps](https://www.powershellgallery.com/packages/dbops). Create multiple deployment configurations, rollback the deployment in case of errors, and even setup Continuous Integration for your database code!
* Optional links (remove if not using)
  * **Twitter**: [@nvarscar](https://twitter.com/nvarscar)
  * **Slack ID**: @nvarscar
  * **Blog URL**: https://nvarscar.wordpress.com

**Comment by RamblingCookieMonster** [comment]
Thanks again!  Do feel free to submit more proposals : D
