### ISSUE TITLE
Learning PowerShell with PSKoans

### ISSUE THREAD

**Issue by vexx32** [PSPowerHour/PSPowerHour#19]
## PSKoans - PowerShell Enlightenment

* **Name**: Joel Sallow
* **Your Timezone**: UTC +5
* **Abstract**: I've a mind to show off the beginnings of the PSKoans module. It's not *complete* yet, but the foundations are quite solid. Cmdlets won't really be covered, but all the general language features of PS will be up for grabs (if we get time for all the weirdness there is to have there!)
* Optional links (remove if not using)
  * **Slack ID**: @Joel_(/u/ta11ow)
  * **Discord ID**: @Joel#2641
  * **Github Repo**: https://github.com/vexx32/PSKoans

**Comment by vexx32** [comment]
Update: Having covered the basic discovery cmdlets and most of the *-Object cmdlets already, I might see what I can pack into a session.

Toying with whether I want to do a sort of run through of how the koans would work in practice or a more stepped-back theoretical 'this is the state of things'. I'm leaning towards the former.

**Comment by RamblingCookieMonster** [comment]
Thanks again!  Do feel free to submit more proposals : D
