### ISSUE TITLE
Default Parameter Values

### ISSUE THREAD

**Issue by potatoqualitee** [PSPowerHour/PSPowerHour#2]
## Default Parameter Values

* **Name**: Chrissy LeMaire
* **Abstract**: `$PSDefaultParameterValues` are ultra useful for automation, scheduled tasks, and even docker but not a lot of people know about this feature. This 5-7 minute session will highlight the value of default parameter values and give real-world examples of how I use them.

  * **Twitter**:  [@cl](https://twitter.com/cl)
  * **Slack ID**: @ cl on [powershell.slack.com](https://bit.ly/psslack)
  * **Slack ID**: @ cl on [sqlcommunity.slack.com](https://sqlps.io/slack)
  * **Blog URL**: [dbatools.io/blog](https://dbatools.io/blog)

**Comment by michaeltlombardi** [comment]
Thank you for speaking today!
