### ISSUE TITLE
Cloning SQL Server Databases using PowerShell

### ISSUE THREAD

**Issue by sanderstad** [PSPowerHour/PSPowerHour#20]
## Cloning SQL Server Databases using PowerShell

* **Name**: Sander Stad
* **Your Timezone**: UTC +2
* **Abstract**: Provisioning databases to our developers or other servers is a lot of hard and takes a lot of time. What if you have a tool set that enables you to clone databases in mere minutes instead of hours or days.
  * **Twitter**: https://twitter.com/SQLStad
  * **Slack ID**: @sqlstad
  * **Blog URL**: https://www.sqlstad.nl/

**Comment by RamblingCookieMonster** [comment]
Thanks again!  Do feel free to submit more proposals : D
