### ISSUE TITLE
Getters and Setters for Classes with Custom Attributes 

### ISSUE THREAD

**Issue by rdbartram** [PSPowerHour/PSPowerHour#21]
## Getters and Setters for Classes with Custom Attribute

* **Name**: Ryan Bartram
* **Your Timezone**: UTC +2
* **Abstract**: Demonstrating how to define getters and Setters for properties in Powershell Classes using custom written attributes. Make properties readonly, set only, validate and manipulate data before it's set. All things that are possible once you have getters and setters
  * **Twitter**: https://twitter.com/rd_bartram
  * **Slack ID**: @rdbartram
  * **Blog URL**: http://www.dftai.ch

**Comment by RamblingCookieMonster** [comment]
Thanks again!  Do feel free to submit more proposals : D

**Comment by vexx32** [comment]
@rdbartram my wife wants me to tell you that she hopes (as do I) that you had a fantastic wedding. ❤️

**Comment by rdbartram** [comment]
Thanks alot! It's actually on the 1st i.e. tomorrow. We're both looking forward to it and appreciate the kinds wishes. Catch you in another pspowerhour, if not sooner in a PSKoans PR ;)
