### ISSUE TITLE
Using PwSH to gather information from silos

### ISSUE THREAD

**Issue by TClark000** [PSPowerHour/PSPowerHour#22]
## Using PwSH to gather information from silos

* **Name**: Teresa Clark
* **Your Timezone**: Your [UTC +1](https://www.timeanddate.com/time/zones/) (e.g. `UTC +1`)
* **Abstract**:  Discuss the constraints and the process involved in creating a PwSH information pipeline.
* **Slack Workspaces**: teresa clark on get-psuguk.slack.com & powershell.slack.com

**Comment by RamblingCookieMonster** [comment]
Hiyo!  Will ping in Slack but in case you miss that and see this - mind sending me your e-mail for some pre-powerhour bits? @pscookiemonster on twitter or powershell.slack.com should work.  Will send some details tonight, and final hangouts link tomorrow at ~ 5:30 PM.  Thanks!

Thanks!

**Comment by RamblingCookieMonster** [comment]
Thanks again!  Do feel free to submit more proposals : D
