### ISSUE TITLE
PowerShell and RegExp to convert code

### ISSUE THREAD

**Issue by ClaudioESSilva** [PSPowerHour/PSPowerHour#23]
## PowerShell and RegExp to convert code

* **Name**: Cláudio Silva
* **Your Timezone**: `UTC +1`
* **Abstract**: I had a project where I needed to convert more than 100K lines of code. Can you imagine the pain of doing it all by hand? I have created an PowerShell function that uses regular expression in order to do the find/replace and used it on +1000 individual files. I did in less than 2 weeks what I initial expected to be several months.
Note: I have used it to convert from Firebird SQL to T-SQL flavor but you can use it to other goals.

* Optional links
  * **Twitter**: [@claudioessilva](https://twitter.com/ClaudioESSilva)
  * **Slack ID**: @claudioessilva on [powershell.slack.com](bit.ly/psslack)
  * **Slack ID**: @claudioessilva on [sqlcommunity.slack.com](https://dbatools.io/slack/)
  * **Blog URL**: https://claudioessilva.eu

**Comment by RamblingCookieMonster** [comment]
Thanks again!  Do feel free to submit more proposals : D
