### ISSUE TITLE
Intro to PSReflect-Functions

### ISSUE THREAD

**Issue by jaredcatkinson** [PSPowerHour/PSPowerHour#25]
## Intro to PSReflect-Functions

* **Name**: Jared Atkinson
* **Your Timezone**: `UTC -7`
* **Abstract**: PSReflect is a PowerShell module that provides a mechanism for calling Windows API functions in PowerShell without the need to compile code at runtime. Unfortunately, the barrier to entry to implementing PSReflect "definitions" is somewhat high. For this reason, I've created an add on module called PSReflect-Functions which is a library that has many Windows API functions exported as a PowerShell function for easy plug and play. This sessions will describe the VERY high level concepts of PSReflect and show some practical use cases for getting started with PSReflect-Functions.
* Optional links (remove if not using)
  * **Twitter**: https://twitter.com/jaredcatkinson

**Comment by RamblingCookieMonster** [comment]
This was awesome, thanks @jaredcatkinson!
