### ISSUE TITLE
2018-08-21 Lineup!

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PSPowerHour/PSPowerHour#29]
Awesome to see so many submissions already : D

So!  Until we have a process around this, going to do things ad hoc / manually-ish

We came up with the following list for our Tuesday, August 21st @ 6:00 PM EST PowerHour:

```
order  created_at          By             title
-----  ----------          --             -----
   01  7/31/18 7:58:16 AM  potatoqualitee Default Parameter Values
   02  7/31/18 5:07:18 PM  dfinke         The dime tour: PowerShell + Excel = Better Together
   03  7/31/18 5:42:21 PM  mattcushing    Import Excel files to SQL Server in less than 20 lines of code, seriously!!
   04  7/31/18 5:49:27 PM  awickham10     Setting Trace Flags as Startup Parameters with dbatools
   05  7/31/18 6:19:44 PM  jpomfret       Applying SQL Server Data Compression with dbatools
   06  7/31/18 6:30:04 PM  alevyinroc     Better, Safer SQL Queries from PowerShell
   07  7/31/18 9:29:51 PM  Windos         Easy Desktop Notifications with BurntToast
   08  7/31/18 11:31:52 PM DanielSSilva   Raspberry Pi with powershell and IoT module
```

@potatoqualitee, @dfinke, @mattcushing, @awickham10, @jpomfret, @alevyinroc - you all are scheduled to give demos, there's no chance you'll be bumped!

@devblackops, @Windos, @DanielSSilva, @wsmelton - you all are on stand-by.  There's a _good_ chance at least the first two of you will speak, perhaps more!  If we run out of time, you'll get precedence at the next PowerHour that fits in your schedule

I'll be working with @michaeltlombardi on a process for an agenda, and an easy way for you to include materials or links to materials for your demos.  This will probably be pretty janky to start with : )

**Please** take a moment and to...

* Let us know if whether you can or can't make it! (thumbs up or thumbs down on this, or just reply)
* Review the repo readme.  This includes various FAQ and details such as...
  * you should show up a few minutes early to make sure you can connect to our YouTube stream!
  * you have 10 minutes max, and shorter demos are even better!
  * there are no live questions, but folks might ping you after in your github issue, or #powerhour in [slack](bit.ly/psslack)

Thanks again, super excited to see these : D

Cheers!

**Comment by RamblingCookieMonster** [comment]
Also, on a scheduling related note, we'll try to get another powerhour in at the end of August or very beginning of September - will post something when we know more!

**Comment by glennsarti** [comment]
@RamblingCookieMonster As per my note - I can't do `(DevOps Culture) Sharing: What's in it for me!?` until after 21st Sept.

Also PLEASE DON'T USE AMERICAN DATES  _end_rant_ :-)

**Comment by Windos** [comment]
ISO 8601, FTW!

Lineup looks good, I'll be there with bells on!

**Comment by dfinke** [comment]
Locked and loaded for 8/21/2018, and for those who are American date challenged, that's 21/08/2018 ;-)

**Comment by alevyinroc** [comment]
I guess I better start rehearsing...

**Comment by RamblingCookieMonster** [comment]
Eek!  updated, I suppose I should read more closely, thanks @glennsarti !

Also, yeah, sorry, posted while juggling babies and reverted to non iso, fixed!

@alevyinroc - that bumps you to a definite : )

**Comment by ctmcisco** [comment]
Assuming other submissions TBD for next round?

**Comment by devblackops** [comment]
@RamblingCookieMonster You can bump me if need be. I'll be in Tokyo on 8/21 and 6PM EDT is 7am in Japan (I think).

**Comment by mattcushing** [comment]
I think I just threw up in my mouth a little :).  I should be good to go, my daughter is leaving for college the next day, do you know what order we're going to go in?

**Comment by RamblingCookieMonster** [comment]
Oh! @mattcushing if you want to hold off (doing another session in short order), we’d be happy to bump you, guessing you have plenty to deal with!

**Comment by mattcushing** [comment]
@RamblingCookieMonster I think I'll be okay.  The big work is going to be packing the cars the next day :)

**Comment by wsmelton** [comment]
Recommended table reference for announcements. It will just provide reference links to the issue being presented and also tie the presenters as participants to the issue.

| Order | Issue Num | Created At | By | Title | Standby |
| --------- | -------- | ------ | ------- | -------- | ----- |
| 01 | #2 | 7/31/18 7:58:16 AM | @potatoqualitee | Default Parameter Values | No |
| 02 | #4 | 7/31/18 5:07:18 PM | @dfinke | The dime tour: PowerShell + Excel = Better Together | No |
| 03 | #5 | 7/31/18 5:42:21 PM | @mattcushing | Import Excel files to SQL Server in less than 20 lines of code, seriously!! | No |
| 04 | #6 | 7/31/18 5:49:27 PM | @awickham10 | Setting Trace Flags as Startup Parameters with dbatools | No |
| 05 | #7 | 7/31/18 6:19:44 PM | @jpomfret | Applying SQL Server Data Compression with dbatools | No |
| 06 | #8 | 7/31/18 6:30:04 PM | @alevyinroc | Better, Safer SQL Queries from PowerShell | No |
| 07 | #10 | 7/31/18 7:58:58 PM | @devblackops | ChatOps with Microsoft Teams and PoshBot | Yes |
| 08 | #11 | 7/31/18 9:29:51 PM | @Windos | Easy Desktop Notifications with BurntToast | Yes |
| 09 | #12 | 7/31/18 11:31:52 PM | @DanielSSilva | Raspberry Pi with powershell and IoT module | Yes |
| 10 | #13 | 8/1/18 12:21:54 AM | @wsmelton | Getting Started with Visual Studio Code | Yes |

**Comment by RamblingCookieMonster** [comment]
Alrighty, bumping @devblackops to the next session.  We should be able to get away with having 9 slots lined up here, not going to backfill this close to the 21st

**Comment by DanielSSilva** [comment]
Just to clarify, this means that i will leave stand by?

**Comment by RamblingCookieMonster** [comment]
Ahh thanks for the reminder, need to draft up notes on who to notify when!  Yeah, so @Windos will no longer be on standby - Brandon was in stand by as well, so this didn't bump anyone into a 'for sure' spot, but it definitely increases the chances of getting to you!

**Comment by DanielSSilva** [comment]
Gotcha! Any ideia when will you know it?

**Comment by RamblingCookieMonster** [comment]
Oh!  I should probably clarify that!  So we have 60 minutes, and all we know about talks is less than 10 minutes (even something like 5 minutes is awesome).

StandBy simply means you'll present if we get to your session before the 60 minute mark.  If 6 people take 10 minutes each, you'll get bumped.  If 7 people take 7 minutes each (you're eighth in the lineup), you'll get in!  Chances are we'll get to the first 2 folks each time... we just don't know for sure until we get through the lineup.

Thanks!

**Comment by RamblingCookieMonster** [comment]
@DanielSSilva - fyi, we changed the format to always do 8 demos, no more idea of 'on deck' to avoid messing with speakers schedules (not to mention the scheduling pain on this side).  You're definitely up for the 21st!

**Comment by michaeltlombardi** [comment]
Done and done, this one is in the books!
