### ISSUE TITLE
Linking meetings in readme.md

### ISSUE THREAD

**Issue by potatoqualitee** [PSPowerHour/PSPowerHour#37]
in a panic, i looked around for the schedule on here, on twitter and on google, then finally looked through the open issues to find when I was scheduled to speak. Please consider copying or (probably) prominently linking to schedule proposals on readme.md. so far, looks like we've got two candidates.

**Comment by wsmelton** [comment]
If this is talking about just linking to the agenda issue that would be pretty clean method to use. Putting the whole agenda though on the readme would get pretty long unless we are talking about just putting the current and maybe the upcoming power hour on it.

You might also use the labeling in GH issues and have an "agenda" and then a "nexthour-agenda". The later one could be used in a floating method where it is assigned to the next agenda that is coming up. Then you just move that label around as they are scheduled.

**Comment by RamblingCookieMonster** [comment]
Yay!  Should be good to go.  Down the line we'll have a bit more automation (well, tooling) around this, but for now, added a link to an agenda.md, and notes on how the repo is organized (e.g. you can pull up /materials/somedate)

Thanks for the reminder on this!
