### ISSUE TITLE
The dime tour: PowerShell + Excel = Better Together 

### ISSUE THREAD

**Issue by dfinke** [PSPowerHour/PSPowerHour#4]
## The dime tour: PowerShell + Excel = Better Together 

A quick tour around my [PowerShell Excel module](https://www.powershellgallery.com/packages/ImportExcel) which lets you import/export Excel spreadsheets, without Excel being installed.

### Doug Finke - 10 time Microsoft MVP

| Catch up with me here|   |
|---|---:|
|Twitter| [@dfinke](https://twitter.com/dfinke)|
|Slack|[@dougfinke](https://powershell.slack.com/dougfinke)|
|Blog URL| [dfinke.github.io](https://dfinke.github.io)|
|GitHub|[@dfinke](https://github.com/dfinke)|
|LinkedIn|[@douglasfinke](https://www.linkedin.com/in/douglasfinke)|
|My book|[PowerShell for Developers](https://www.amazon.com/Windows-PowerShell-Developers-Productivity-Application/dp/1449322700)|

**Comment by potatoqualitee** [comment]
lol dime tour, i love it

**Comment by mattcushing** [comment]
I can even follow him up with how someone with zero Powershell experience can use his module :)

**Comment by michaeltlombardi** [comment]
Thank you so much for presenting today!
