### ISSUE TITLE
Writing and Deploying a VSTS Extension in 10 Minutes or Less

### ISSUE THREAD

**Issue by ThmsRynr** [PSPowerHour/PSPowerHour#47]
Title: "Writing and Deploying a VSTS Extension in 10 Minutes or Less"
Name: Thomas Rayner
Timezone: 'Pacific Standard Time'
Abstract: |
    VSTS build and deploy extensions are incredibly powerful and flexible modules that can be installed from the Visual Studio marketplace, or developed and deployed yourself. In this no-slides-session, I'll show you how quickly you can get started writing and deploying your very own VSTS extensions.
Twitter: '@MrThomasRayner'
SlackID: 'mrthomasrayner'
Blog: 'https://workingsysadmin.com'

**Comment by ThmsRynr** [comment]
@Jaykul Yeah this one is gonna have to fly. I might be getting the inaugural hook for going over if there are any demo issues :smile:

**Comment by RamblingCookieMonster** [comment]
This was awesome, thanks @ThmsRynr!
