### ISSUE TITLE
Add YouTube time offset links

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PSPowerHour/PSPowerHour#52]
materials/date/readme table might be a good spot to have links to each talk.  These readme's are initially generated, but wouldn't hurt to manually add links to the start of each talk (e.g. Daniel starts [here](https://youtu.be/fDQvdIEda_c?t=3278))

**Comment by ClaudioESSilva** [comment]
Ups, don't saw this issue before submitting PR https://github.com/PSPowerHour/PSPowerHour/pull/53.

Please see if it helps
