### ISSUE TITLE
Setting Trace Flags as Startup Parameters with dbatools

### ISSUE THREAD

**Issue by awickham10** [PSPowerHour/PSPowerHour#6]
## dbatools - Setting Trace Flags as Startup Parameters
Database Administrator at Westfield

* **Name**: Andrew Wickham
* **Abstract**: How to set trace flags across your SQL Server landscape using the dbatool PowerShell module (Set-DbaStartupParameter and Enable-DbaTraceFlag functions)
* Optional links (remove if not using)
  * **Twitter**: https://twitter.com/awickham

**Comment by michaeltlombardi** [comment]
Question from @MSAdministrator:

> Have you thought of using Docker-Compose to setup all the containers?

**Comment by awickham10** [comment]
Definitely love Docker-Compose! I have a few setup like that for my home theater and home networking setups. If I keep presenting on this I'll probably do that. Thanks for the suggestion!

**Comment by michaeltlombardi** [comment]
Thank you so much for presenting today!
