### ISSUE TITLE
Applying SQL Server Data Compression with dbatools

### ISSUE THREAD

**Issue by jpomfret** [PSPowerHour/PSPowerHour#7]
## Applying SQL Server Data Compression with dbatools

* **Name**: Jess Pomfret
* **Abstract**: Discover good candidates for row or page compression and then easily apply the recommended compression across your database.
* Optional links (remove if not using)
  * **Twitter**: https://twitter.com/jpomfret
  * **Slack ID**: jpomfret7
  * **Blog URL**: http://jesspomfret.com

**Comment by michaeltlombardi** [comment]
Thank you so much for presenting today!
