### ISSUE TITLE
Better, Safer SQL Queries from PowerShell

### ISSUE THREAD

**Issue by alevyinroc** [PSPowerHour/PSPowerHour#8]
## Better, Safer SQL Queries from PowerShell

* **Name**: Andy Levy
* **Abstract**: If you're working with SQL Server from PowerShell, either as a DBA, analyst, or anyone else running queries, you've probably used `Invoke-SqlCmd`. But depending on how you're building your queries, this can be error-prone or a huge security exposure! With the help of the `dbatools` module, I'll show you how to write and run these queries better and safer - and make them easier to work into your scripts to boot.
* Optional links (remove if not using)
  * **Twitter**: https://twitter.com/alevyinroc
  * **Slack ID**: @alevyinroc
  * **Blog URL**: https://therestisjustcode.wordpress.com/
  * **Timezone**: America/New_York

**Comment by michaeltlombardi** [comment]
Thank you so much for presenting today!
