### ISSUE TITLE
2018-11-20 6:00 PM PST Lineup planning

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PSPowerHour/PSPowerHour#98]
Hiyo!

EDIT: Here's the schedule (It may change):

Order | By             | IssueNumber | Title
----- | -------------- | ----------- | ------------------------------------------------------------------------
01    | @glennsarti    | #17         | (DevOps Culture) Sharing: What's in it for me!?
02    | @ctmcisco      | #79         | Using the Automated Lab Framework to deploy a lab on Hyper-V Server 2016
03    | @devblackops   | #10         | ChatOps with Microsoft Teams and PoshBot
04    | @scrthq        | #97         | Getting Started with PowerShell Core in AWS Lambda
05    | @awickham10    | #99         | PSFramework - Logging to Graylog
06    | @KirkMunro     | #100        | Coming soon to a debugger near you
07    | @vexx32        | #101        | Getting Started: Contributing to PowerShell Core
08    | @steviecoaster | #94         | Bitlocker and Powershell

Michael's been busy planning for a wedding, getting married, and other things : )  I've been enjoying delaying the roughly-two-mortgages cost of daycare.  Soooo we've been slow.

The plan was to recruit folks and get a 6:00 PM PST, and 6:00 PM UTC session going on back to back days, to get more timezones in play.  That didn't happen : )

So!

Anyone up for a 6:00 PM PST PSPowerHour on November 20?

cc @scrthq, @steviecoaster, @ChrisLGardner, @ctmcisco, @MSAdministrator, @potatoqualitee, @devblackops, @kjacobsen, @mattcushing - Including mostly everyone - no worries if timezones don't work out Chrissy and Chris!

Let me know!  Will harass folks on twitter now : )  Sorry for being so slow to get the next PowerHour planned!

Open spots:  0 of 8!
Taken slots:  @glennsarti, @ctmcisco, @steviecoaster, @devblackops, @scrthq, @awickham10, @KirkMunro, @vexx32

**Comment by devblackops** [comment]
@RamblingCookieMonster I'm good with that time slot! I can talk about PoshBot and Teams.

**Comment by scrthq** [comment]
I'm there, that timeslot is perfect for me. Looking forward!

**Comment by steviecoaster** [comment]
I'm good with that slot. I can ramble about Bitlocker for a bit!

**Comment by glennsarti** [comment]
@RamblingCookieMonster Count me in.  Issue #17   Just to confirm that this will start 18:00 PST (PST) Nov 20, which is 10:00 AWST (GMT +8) on Nov 21.

**Comment by RamblingCookieMonster** [comment]
Thanks for making this happen @glennsarti, @ctmcisco, @steviecoaster, @devblackops, @scrthq, @awickham10, @KirkMunro, @vexx32!

**Comment by vexx32** [comment]
Glad to have been able to contribute a little something! 😄
